# 에러 처리 

- 에러에 가능성을 항상 생각해서 프로그램이 강제 종료되지 않게 대응하는게 중요

```javascript
// 예를들어 DOM에서 요소 노드를 찾을수 없는 경우 (아직 만들어지지 않았을때 등) $button에는 null이 담길수도 있음
const $button = document.querySelector('button')
$button.classList.add('disabled') // 이때 이 요소에 클래스를 추가해주려고 하면 TypeError: cannot read property classList of null 가 발생
$button.classList.add('disabled') // 이때 이 요소에 클래스를 추가해주려고 하면 TypeError: 

// 이 경우를 대비해서 null이 아닐경우만 (옵셔널 체이닝) classList에 disabled class를 추가하도록 하는 대응이 필요함
$button?.classList.add('disabled')

```

## try, catch, finally 문

- 에러 처리를 하는 방법중 하나로써 에러가 발생할 가능성이 있는 코드를 try에 적어주고 발생한 에러는 catch문의 인수로 전달해서 에러 처리 작업을 함으로써 프로그램이 강제 종료되는걸 막음.

```javascript
try {
  // 에러가 발생할수 있는 코드
} catch (err) {
  // 에러가 발생했을때 실행할 코드
  console.error(err)
} finally {
  // 코드의 성공/실패 여부와 상관없이 한번 실행시킬 코드
  console.log('Bye')
}

```

## Error 객체

- Error 생성자 함수를 통해 error 객체를 생성할수 있음 
- Error 내용을 설명하는 메세지를 인수로 전달 할수 있음

```javascript
const err = new Error('custom error message')
```

- 총 7가지 에러 객체를 생성할수 있는 Error 생성자 함수를 제공
- Error, SyntaxError, ReferenceError, TypeError, RangeError, URIError, EvalError

## throw 문

- Error 객체를 생성한다 해서 에러가 발생하진 않음. 
- 에러를 발생시키기 위해선 `throw 표현식(주로 에러 객체)` 으로 에러 객체를 '던저' 줘야함

```javascript
try {
throw new Error('custom error');
} catch (error) {
  console.log(error) // Error: custom error
} 
```

- 에러는 호출자 방향으로 전파됨
- throw 된 에러를 어디에서도 캐치하지 않으면 프로그램은 강제 종료됨